build:
  nodes:
    coverage:
      tests:
        override:
          command: "export JWT_SECRET='L0ngS3cr3tK3y!'"
          command: "chmod +x db/reset_test_db.bash"
          command: "npm test"
            coverage:
              file: coverage/clover.xml
              format: clover